# Generated by Django 4.2.3 on 2023-08-04 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table_movie',
            name='img',
            field=models.ImageField(default='ghghkimg', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
